version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=management.settings
      - POSTGRES_DB=drone_musala
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=drone_musala
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=musala
    ports:
      - 5431:5432

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    build: .
    command: celery -A management.celery worker --pool=solo --loglevel=warning -f battery.log -l INFO
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: management.settings
    depends_on:
      - postgres
      - redis
      
  beat:
    build: .
    command: celery -A manage.celery beat -l info
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: management.settings      
    depends_on:
      - postgres
      - redis

